# -*- coding: utf-8 -*-
"""SHAILJA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1of1_5LLhDj2Q3_hxvsQPyiFuSYE7VLJd
"""

!pip install ultralytics

from ultralytics import YOLO
import os
import json
from collections import Counter

# Paths
yaml_path = "/content/drive/MyDrive/computer vision_yolov8/data.yaml"
test_images_path = "/content/drive/MyDrive/computer vision_yolov8/test/images"
output_json_path = 'final_counts.json'

# Step 1: Load and Train the Model
model = YOLO('yolov8s.pt')  # <--- Changed here!

# Train
model.train(
    data=yaml_path,
    epochs=30,
    imgsz=640,
    batch=16,
    name='custom_object_detection_model'
)

# Step 2: Load Trained Model
trained_model_path = 'runs/detect/custom_object_detection_model/weights/best.pt'
model = YOLO(trained_model_path)

# Step 3: Run Inference
results = model.predict(test_images_path, save=False)

# Step 4: Parse Inference Results
class_names = ['Product-Name', 'Empty-Space', 'Other-Product']

# Initialize counter
counts = Counter({name: 0 for name in class_names})

for result in results:
    boxes = result.boxes
    for box in boxes:
        cls_id = int(box.cls[0].item())  # Get class ID
        cls_name = class_names[cls_id]
        counts[cls_name] += 1

# Step 5: Save Final Counts to JSON
with open(output_json_path, 'w') as f:
    json.dump(counts, f, indent=4)

print(f"Final counts saved to {output_json_path}")
print(counts)

